### ISSUE TITLE
No update the pools map when you create a new pool, it is a bug?

### ISSUE THREAD

**Issue by davidwudv** [mediocregopher/radix.v2#10]
hello, I am using your project and have a question, in cluster.(c *Cluster).getconn(key, addr string) function, when you creat a new pool, but miss :

``` Go
c.pools[addr] = p
```

It is a bug?

**Comment by mediocregopher** [comment]
thanks for submitting the issue! From a brief glance at the code I think you may be right, this is likely a bug, albeit one not likely to happen often, but definitely something which needs to be taken care of. Not that it matters too much, but would you be able to tell me how you ran into this at all?

**Comment by davidwudv** [comment]
@mediocregopher I didn't run into this, I found it when I review this code

**Comment by davidwudv** [comment]
@mediocregopher thanks for your reply.
I didn't run into this, I just found it when I review this code, and I think logically should update the pools map.

**Comment by mediocregopher** [comment]
Hopefully that takes care of it, thanks for looking through the code, please feel free to let me know of any other issues you see!

**Comment by davidwudv** [comment]
OK
