### ISSUE TITLE
Cluster.Cmd() returns "OK" instead of nil or a value.

### ISSUE THREAD

**Issue by tpiron** [mediocregopher/radix.v2#14]
At some point, when we query our redis cluster using Cluster.Cmd(), it returns "OK".

Did you ever experienced a similar issue ?

I'll try to get more details asap.

**Comment by mediocregopher** [comment]
I'm definitely going to need more details than that :P Keep in mind some redis commands actually do return "OK" (like [SET](http://redis.io/commands/SET)), so maybe you're just not handling the return from one of those properly?

**Comment by mediocregopher** [comment]
I'm going to go ahead and close this issue, please feel free to re-open it if you're still seeing problems or if you want any help debugging, I'm happy to help :)
