### ISSUE TITLE
Unable to find a way to use Redis AUTH and Pool at same time

### ISSUE THREAD

**Issue by pschlump** [mediocregopher/radix.v2#24]
So far - I am unable to find a way to authorized connections that are pooled.  I need to iterate across
the pooled connections and run an "AUTH "mypasswordkey"".

I am going to fork and implement an ".Auth" that performs this.

**Comment by mediocregopher** [comment]
Hey pschlump! there's no need to make a fork to do this, you can use `pool.NewCustom` in order to do what you want. See the example in the godocs [here](https://godoc.org/github.com/mediocregopher/radix.v2/pool#hdr-Custom_connections)
