### ISSUE TITLE
Would you like to implement a reliable message queue using `RPOPLPUSH`?

### ISSUE THREAD

**Issue by Akagi201** [mediocregopher/radix.v2#30]
similar project: https://github.com/adjust/rmq

**Comment by mediocregopher** [comment]
Looks like one already exists :P You could also check out https://github.com/mc0/okq which I worked on with some other friends, it's currently being used in production at my current company and it's working out pretty great. Hope this helps!

**Comment by mediocregopher** [comment]
Also I should say that antirez is discussing adding kafka-style queues to redis as a builtin type, which will be interesting and is definitely something to keep an eye out for, as that would probably cover your use-case as well once it's out.

**Comment by Akagi201** [comment]
@mediocregopher Nice job!!! Very nice project.

**Comment by mediocregopher** [comment]
Thanks! :D
