### ISSUE TITLE
the Redis Cluster client cannot support auth  

### ISSUE THREAD

**Issue by andyli029** [mediocregopher/radix.v2#31]

**Comment by andyli029** [comment]
fix the Redis Cluster client to support auth in the Func of NewWithOpts #32 
 @mediocregopher

**Comment by mstoykov** [comment]
Hi. 
The DialFunc idea is that you create your own and then use that. In it you can do everything you would like to do before the making the connection(some complicated knock mechanism to open a port ...) and before that connection can be used(sending AUTH and/or SELECT ...). 

The cluster package docs don't have example, but there is one in the [pool](https://godoc.org/github.com/mediocregopher/radix.v2/pool).

**Comment by mediocregopher** [comment]
@MStoykov is correct, the purpose of the DialFunc is to allow for things like AUTH within it. The pool's example works just as well for cluster. I'm going to close your PR and this issue, but thanks for contributing and please don't be discouraged in the future!
