### ISSUE TITLE
Username and password

### ISSUE THREAD

**Issue by azzuwan** [mediocregopher/radix.v2#35]
I'm connecting to Redis Cloud, how do I specify the username and password?

**Comment by mediocregopher** [comment]
According to their docs it would seem that you authenticate using a normal `AUTH` command. I'm not super familiar with redis cloud though, but here's their docs on the subject:

https://redislabs.com/redis-howto?page_source=cloud#connecting-to-redis

**Comment by mediocregopher** [comment]
Hopefully that helped, feel free to reopen this if you have any more questions :)
