### ISSUE TITLE
why did you have the release

### ISSUE THREAD

**Issue by andyli029** [mediocregopher/radix.v2#37]

**Comment by mediocregopher** [comment]
Hey dude, sorry I didn't get back on this, I'm not quite sure what you're asking, can you elaborate?

**Comment by andyli029** [comment]
the release  is the release package:
[releases](https://github.com/mediocregopher/radix.v2/releases)

**Comment by mediocregopher** [comment]
That page is something github provides on every project, but for go projects it's not very useful because there's no versioning anyway, so (theoretically) as long as you have the latest version you're fine. Not quite sure if that answers your question, lemme know if it doesn't.

**Comment by mediocregopher** [comment]
I'm gonna go ahead and close this, please feel free to reopen if you have any more questions though :)
