### ISSUE TITLE
Why put closed connection into the pool in NewCustom

### ISSUE THREAD

**Issue by chrislee87** [mediocregopher/radix.v2#54]
When err occurs, redis-client is closed, why still put those clients into the pool
_**if err != nil {
	for _, client = range pool {
		client.Close()
	}
	pool = pool[0:]
	break
}**_
Is that you want to return an empty pool, should the code be as below
_**pool = pool[:0]**_

**Comment by mediocregopher** [comment]
Great catch, thanks!
