### ISSUE TITLE
Check for nil?

### ISSUE THREAD

**Issue by danqing** [mediocregopher/radix.v2#6]
Correct me if I'm missing something, but I don't see a way to check if, for example, a `GET` returns `nil`?

``` go
r := client.Cmd("GET", "key")
if r.IsType(redis.Nil) // This won't work since Nil = 7 and IsType is bitwise &
```

Thanks!

**Comment by mediocregopher** [comment]
I'm sorry it's taken so long to respond, for some reason github decided I shouldn't receive notifications for issues on the repo >_<

The definition for that set of constants is `1 << iota`, which means `Nil`'s value is `1 << 7`, or 128. So your check is correct.
