### ISSUE TITLE
does it support pipeline in cluster mode?

### ISSUE THREAD

**Issue by justme9527** [mediocregopher/radix.v2#65]
does it support pipeline in cluster mode?

**Comment by mediocregopher** [comment]
In a sense yes. If you use the `GetForKey` method on Cluster it will return a Client, and you can do whatever you like to that Client before you Put it back. This includes the normal Pipeline commands (PipeAppend, PipeResp).

However note that if the cluster topology changes while you "own" the Client (i.e. before you Put it back) your pipeline may return related errors like MOVED or ASK, which would normally be handled automatically by Cluster's Cmd method, but in this case won't be. You'll just have to try your pipeline again with another Client and hope the topology has figured itself out.
