### ISSUE TITLE
Does redis.Client have auto reconnecting? Can I use more than one sentinel?

### ISSUE THREAD

**Issue by lxyscls** [mediocregopher/radix.v2#74]
Hi, I am a newbie for Go.

- Is there any auto reconnecting on redis.Client? 

- If I have more than one sentinel, do i need to create multi sentinel.Client, then loop each sentinel, call GetMaster? Is there any auto mechanism to get redis.Client from sentinel bulk?

Appreciate your reply!

**Comment by mediocregopher** [comment]
Hi @lxyscls! To directly answer your questions:

* No, Client doesn't do auto-reconnecting. That sort of behavior is handled by wherever you got the Client from (e.g. [pool](https://godoc.org/github.com/mediocregopher/radix.v2/pool) or [sentinel](https://godoc.org/github.com/mediocregopher/radix.v2/sentinel) or [cluster](https://godoc.org/github.com/mediocregopher/radix.v2/cluster). You shouldn't ever really have to think extra about reconnection. No matter what you should expect that any `Cmd` call could return an error, either from the Client being disconnected or the redis instance simply being down.

* No, the sentinal.Client doesn't currently support multiple sentinel instances.

To give a more helpful answer to your second question, I'd recommend checking out [radix.v3](https://godoc.org/github.com/mediocregopher/radix.v3), which has a sentinel client which does support multiple instances, and which is just better in general :)

**Comment by lxyscls** [comment]
@mediocregopher thanks for your reply! I will try.
