### ISSUE TITLE
some suggestions

### ISSUE THREAD

**Issue by iiinsomnia** [mediocregopher/radix.v2#75]
* connectTimeout、writeTimeout、readTimeout should be set up separately;

* Interval time of PING should be set up

**Comment by iiinsomnia** [comment]
It would be better to add `maxOpenConns` and `maxIdleConns` for pool

**Comment by mediocregopher** [comment]
Hi @IIInsomnia! Thank you for the suggestions. You're right that the connect and write/read timeouts might be better being settable separately. I'm not sure I agree with your suggestions for how the pool can be changed, but at any rate this particular API is pretty set in stone at this point and it'd be difficult to be changed.

If you'd like, you can check out [radix.v3](https://github.com/mediocregopher/radix.v3) which is basically stable and allows for much greater customization of individual components, so even if you disagree with how I've implemented some part of it you should be able to switch it out with your own implementation fairly simply.
