### ISSUE TITLE
Sentinel client does not support operations on slaves

### ISSUE THREAD

**Issue by atomr3** [mediocregopher/radix.v2#89]
Currently, all operations with Redis sentinel appear to go via the current master connection, which will not work well when attempting to scale reads. I propose injecting functionality to connect to slave nodes and execute queries on those instances.

**Comment by mediocregopher** [comment]
I'm afraid the way the sentinel package in this project is designed makes doing this rather difficult, and I'm focusing on getting the next version of this project, [radix.v3](https://github.com/mediocregopher/radix.v3), ready to be promoted, so it would be better if I instead focus on making sure this use-case is handled in v3. Thanks for submitting the issue, I'm sorry that I'm not going to be able to make it happen.
