### ISSUE TITLE
How to connect to redis cloud that's password protected?

### ISSUE THREAD

**Issue by kingcw** [mediocregopher/radix.v2#90]
Hi,

how to use radix.v2 pool to connect to redis cloud that's password protected?

 i don't see a password parameter for New function: pool.New("tcp", address, 10)

for address, i tried to add password :password@host:port, and it's not working neither

Thank you

**Comment by mediocregopher** [comment]
Hey @kingcw, if you check out the [docs for the pool package](https://godoc.org/github.com/mediocregopher/radix.v2/pool), under the title "Custom connections" you can find an example for a pool which uses AUTH connections.
