### ISSUE TITLE
Hope `HGETALL` support `ScanStruct` function like `redigo`

### ISSUE THREAD

**Issue by iiinsomnia** [mediocregopher/radix.v2#92]

**Comment by mediocregopher** [comment]
Hey @IIInsomnia, thanks for the feature request! unfortunately I've pretty much stopped development on this package in favor of its sequel, [radix.v3](https://github.com/mediocregopher/radix.v3). But I'll go ahead and make a note to look into adding support for this there

**Comment by iiinsomnia** [comment]
Thanks a lot !
