### ISSUE TITLE
-

### ISSUE THREAD

**Issue by kayalardanmehmet** [mediocregopher/radix.v2#93]
I need to listen expired events in my application. As I know, keyspace notifications are node-specific unlike regular pub/sub. So, to catch expired events for all keys I need to attach all nodes in cluster mode. How can I achieve this with radix? I couldn't find any solution.

**Comment by mediocregopher** [comment]
Hey @kayalardanmehmet, I answered your issue in the newer radix package, and this one is no longer maintained, so I'm going to go ahead and close this.
